version: "3"

services:
    nginx:
        container_name: nginx
        build: "./requirements/nginx/"
        depends_on:
            - wordpress
            - game
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html/
        networks:
            - bridgeNetwork
        env_file:
            - .env
        restart: always
    wordpress:
        container_name: wordpress
        build: "./requirements/wordpress/"
        depends_on:
            - mariadb
            - redis
        volumes:
            - wordpress:/var/www/html/
        networks:
            - bridgeNetwork
        env_file:
            - .env
        restart: always
    mariadb:
        container_name: mariadb
        build: "./requirements/mariadb/"
        depends_on:
            - redis
        volumes:
            - sql:/var/lib/mysql/
        networks:
            - bridgeNetwork
        env_file:
            - .env
        restart: always
    redis:
        container_name: redis
        build: "./requirements/bonus/redis/"
        networks:
            - bridgeNetwork
        env_file:
            - .env
        restart: always
    ftp:
        container_name: ftp
        build: "./requirements/bonus/ftp/"
        ports:
            - "21:21"
            - "21100-21110:21100-21110"
        volumes:
            - wordpress:/var/www/html
        networks:
            - bridgeNetwork
        env_file:
            - .env
        restart: always
    game:
        container_name: game
        build: "./requirements/bonus/game/"
        ports:
            - "3000:3000"
        networks:
            - bridgeNetwork
        env_file:
            - .env
        restart: always
    adminer:
        container_name: adminer
        build: "./requirements/bonus/adminer"
        depends_on:
            - mariadb
            - wordpress
        ports:
            - "8080:8080"
        networks:
            - bridgeNetwork
        env_file:
            - .env
        restart: always
    portainer:
        container_name: portainer
        build: "./requirements/bonus/portainer"
        ports:
            - "9443:9443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "portainer_data:/data"
        networks:
            - bridgeNetwork
        env_file:
            - .env
        restart: always

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: ./wp_volume/
            o: bind
            type: none
    sql:
        name: sql
        driver: local
        driver_opts:
            device: ./sql_volume/
            o: bind
            type: none
    portainer_data:
        name: portainer
        driver: local
        driver_opts:
            device: ./portainer_data/
            o: bind
            type: none

networks:
    bridgeNetwork:
        name: bridgeNetwork
        driver: "bridge"
